### ISSUE TITLE
first time trying this?

### ISSUE THREAD

**Issue by postpwn** [ricardojoserf/instagram-followers-bot#1]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import aux_funcs, sys, json, time, random
  File "/Users/justin/Desktop/instagram-followers-bot/aux_funcs.py", line 1, in <module>
    import sys, json, requests, os

**Comment by ricardojoserf** [comment]
I think installing requests package with pip fixes this!
Tell me if it does or not, and sorry for my really-late response xD
