### ISSUE TITLE
Error INFO

### ISSUE THREAD

**Issue by jose46moreno** [ricardojoserf/instagram-followers-bot#10]
Hi, Ricardo,

I've seen that you're from Madrid, but if it's of any use to anyone else, I'll leave it in English.

I'm having trouble trying the first command to get the info.

I've seen that it's a recurrent report that you already fixed but I wanted to know if there was something changed in the API that could cause me the error.

I attach the error reported by the terminal (Mac):

Login not successful
Traceback (most recent call last):
  File "main.py", line 157, in <module>
    main()
  File "main.py", line 113, in main
    for i in api.getTotalSelfFollowers():
  File "/Users/josepfm/Desktop/instagram-followers-bot-master/LevPasha/InstagramAPI.py", line 163, in getTotalSelfFollowers
    return self.getTotalFollowers(self.username_id)
AttributeError: 'InstagramAPI' object has no attribute 'username_id'

**Comment by jose46moreno** [comment]
@ricardojoserf puedes ayudarme?

Perdona la molestia y muchas gracias por tu gran trabajo!
