### ISSUE TITLE
error in super-unfollow

### ISSUE THREAD

**Issue by daddyparodz** [ricardojoserf/instagram-followers-bot#22]
- Expected vs Actual Behavior

Expected? Idk because I haven't actually seen what it does.
Actual behavior:

python3.8:

Traceback (most recent call last):
  File "main.py", line 157, in <module>
    main()
  File "main.py", line 140, in main
    super_unfollow()
  File "main.py", line 94, in super_unfollow
    user_id = aux_funcs.get_id(i)
  File "/home/bob/instagram-followers-bot/aux_funcs.py", line 19, in get_id
    respJSON = response.json()
  File "/home/bob/.local/lib/python3.8/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

python 2.7:

Traceback (most recent call last):
  File "main.py", line 157, in <module>
    main()
  File "main.py", line 140, in main
    super_unfollow()
  File "main.py", line 94, in super_unfollow
    user_id = aux_funcs.get_id(i)
  File "/home/bob/instagram-followers-bot/aux_funcs.py", line 19, in get_id
    respJSON = response.json()
  File "/home/bob/.local/lib/python2.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

- Specifications

tested both in python3.8 and python2.7, trowing error when trying to unfollow. info is working fine.

 - Operative system:
 
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

 - Version (e.g. Python version):
python 2.7 and 3.8

- Steps to Reproduce the Problem

python3.8: python3 main.py -u USERNAME -p PASSWORD -o super-unfollow
python2.7: python2.7 main.py -u USERNAME -p PASSWORD -o super-unfollow

**Comment by ricardojoserf** [comment]
Hi @daddyparodz , I think it could be because the credentials used are nott valid, I just tested it and it is working

**Comment by FaBeyyy** [comment]
No it does not. Info works but i get the same error when executing super unfollow

**Comment by ricardojoserf** [comment]
Hi you are right, I will reopen the issue until I can fix it

**Comment by ricardojoserf** [comment]
Hi @daddyparodz  and @FaBeyyy !!! Please check if it works now, I hope so (please dpwnload the latest version :))

**Comment by daddyparodz** [comment]
Thank you! Now it works perfectly!
