### ISSUE TITLE
Do you still support it?

### ISSUE THREAD

**Issue by UnixCro** [ricardojoserf/instagram-followers-bot#23]
The project is a bit older, would be sad if you no longer support it

**Comment by ricardojoserf** [comment]
Hi @UnixCro ! Yes I still support it in the way that if a functionality stops working I will try to fix it when I have time, but I am not planning on adding more functionalities, at least while I don¡t have time for it. I hope that solves your question :)

**Comment by UnixCro** [comment]
The reason I ask is that unfortunately it doesn't work for me under macOS and when
I saw the last year of corrections I was a little clear.

Since I don't have a lot of knowledge about Python and the other stuff I'll show you 
what comes out with me.

```
pip3 install -r requirements.txt 

Requirement already satisfied: requests==2.20.0 in /Library/Python/3.8/site-packages (from -r requirements.txt (line 1)) (2.20.0)
Requirement already satisfied: requests_toolbelt==0.8.0 in /Library/Python/3.8/site-packages (from -r requirements.txt (line 2)) (0.8.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /Library/Python/3.8/site-packages (from requests==2.20.0->-r requirements.txt (line 1)) (1.24.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Python/3.8/site-packages (from requests==2.20.0->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in /Library/Python/3.8/site-packages (from requests==2.20.0->-r requirements.txt (line 1)) (2.7)
Requirement already satisfied: certifi>=2017.**4.17 in /Library/Python/3.8/site-packages (from requests==2.20.0->-r requirements.txt (line 1)) (2020.6.20)

```
```
myhome@mypcname instagram-followers-bot % python3.6 main.py
 
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import aux_funcs, sys, json, time, random
  File "/Users/myhomeDownloads/instagram-followers-bot/aux_funcs.py", line 1, in <module>
    import sys, json, requests, os
ModuleNotFoundError: No module named 'requests'

```

**Comment by ricardojoserf** [comment]
Hi! Could you try this?
"pip3 install requests"

**Comment by UnixCro** [comment]
Yes I have

```
myhome@mypcname instagram-followers-bot % /usr/bin/pip3 install requests         
Requirement already satisfied: requests in /Library/Python/3.8/site-packages (2.20.0)
Requirement already satisfied: idna<2.8,>=2.5 in /Library/Python/3.8/site-packages (from requests) (2.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Python/3.8/site-packages (from requests) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /Library/Python/3.8/site-packages (from requests) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Python/3.8/site-packages (from requests) (2020.6.20)
```

**Comment by ricardojoserf** [comment]
Hi, I think you are running the script with Python 3.6 but maybe the installed version of requests is with Python 3.8
Could you try running "pip3.6 install requests" and try again or run the script with "python3" or "python3.8"?

**Comment by UnixCro** [comment]
Honor man!
Very cool it worked right away

```
myhome@mypcname instagram-followers-bot % pip3.6 install -r requirements.txt                                          
Requirement already satisfied: requests==2.20.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (2.20.0)
Requirement already satisfied: requests_toolbelt==0.8.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (0.8.0)
Requirement already satisfied: idna<2.8,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests==2.20.0->-r requirements.txt (line 1)) (2.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests==2.20.0->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests==2.20.0->-r requirements.txt (line 1)) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests==2.20.0->-r requirements.txt (line 1)) (2020.12.5)
```

And then it worked

```
myhome@mypcname instagram-followers-bot % python3.6 main.py                                               
usage: main.py [-h] -u USER -p PASSWORD -o OPTION [-t TARGET] [-i IMAGE]
               [-c CAPTION]
main.py: error: the following arguments are required: -u/--user, -p/--password, -o/--option
```

If you have the time, you can manage the specified passwords like with "instaloader" so that they are saved, but only the program itself can decrypt them and no other program, otherwise you have to enter your passwords repeatedly. I think that would be great.

I also have the message "(Max val: 100")
Can you maybe tell me what that means

Otherwise, thanks for the quick and effective help. Stay healthy

**Comment by ricardojoserf** [comment]
You are welcome! Feel free to like the repo or follow me  :) 
I think the message means you can follow up to 100 people at the same time.
stay healthy too!
