### ISSUE TITLE
Error after runing the program

### ISSUE THREAD

**Issue by bfgelectronics** [ricardojoserf/instagram-followers-bot#26]
## Expected vs Actual Behavior
The program worked and unfollowed like 10 but now it gives me an error.

## Specifications

 - Operative system:  Raspbian

 - Version (e.g. Python version): 2.7.16

## Steps to Reproduce the Problem

When I run the program , after a few seconds I get this error message:
Traceback (most recent call last):
  File "main.py", line 158, in <module>
    main()
  File "main.py", line 144, in main
    unfollowall()
  File "main.py", line 105, in unfollowall
    user_id = aux_funcs.get_id(i)
  File "***/instagram-followers-bot-master/aux_funcs.py", line 19, in get_id    // I censored the actual location with ***
    respJSON = response.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ricardojoserf** [comment]
Hi @bfgelectronics !!!
Please change the value of the variables in lines 10 and 11:
min_delay = 5
max_delay = 10

To a higher value, for example:
min_delay = 10
max_delay = 20

And please let me know if this problem still exists :)

**Comment by ricardojoserf** [comment]
Hi! Please download the dev branch (https://github.com/ricardojoserf/instagram-followers-bot/tree/dev) and let me know if this works better or the same ;) It seems it worked for this issue, which is the same that this one - https://github.com/ricardojoserf/instagram-followers-bot/issues/27

**Comment by ricardojoserf** [comment]
Hi! I merged the dev branch and this problem seems fixed :) Let me know if this keeps happening in the future, thank you for opening the issue @bfgelectronics !

**Comment by bfgelectronics** [comment]
Probably my problem it's because instagram is blocking my requests. Now I tryed with the " watch -n 3600 " in front of the command and in 1 week it already unfollowed around 4k following users
