### ISSUE TITLE
ERROR import: unable to open X server `' @ error/import.c/ImportImageCommand/364.

### ISSUE THREAD

**Issue by 776166** [ricardojoserf/instagram-followers-bot#6]
Ubuntu 18.04 LTS, command line without GUI.

```
./main.py -u username -p pass -o unfollow-all
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
from: too many arguments
./main.py: line 4: followers: command not found
./main.py: line 5: followings: command not found
./main.py: line 6: syntax error near unexpected token `('
./main.py: line 6: `args = aux_funcs.get_args()'
```

**Comment by 776166** [comment]
#!/usr/bin/env python in head needed

**Comment by ricardojoserf** [comment]
Hi, i think you can also use "python main.py..."

Cheers

**Comment by 776166** [comment]
Anyway script do not works. :(

```
Login not successful
Traceback (most recent call last):
  File "main.py", line 157, in <module>
    main()
  File "main.py", line 113, in main
    for i in api.getTotalSelfFollowers():
  File "/home/madget/tmp/instagram-followers-bot/LevPasha/InstagramAPI.py", line 162, in getTotalSelfFollowers
    return self.getTotalFollowers(self.username_id)
AttributeError: InstagramAPI instance has no attribute 'username_id'
```

**Comment by ricardojoserf** [comment]
Hi @776166 . That error occurs when you use it too much. Wait for four or five hours and try again please ;)

Cheers,

Ricardo

**Comment by 776166** [comment]
Thanks.
But I think that it is error "checkpoint_challenge_required". Because additional auth required.

```
Request return 400 error!
{u'status': u'fail', u'message': u'challenge_required', u'error_type': u'checkpoint_challenge_required', u'challenge': {u'api_path': u'/challenge/3017060448/hfWjwRnBPV/', u'native_flow': True, u'url': u'https://i.instagram.com/challenge/3017060448/hfWjwRnBPV/', u'lock': True, u'logout': False, u'hide_webview_header': True}}
```
Not from your script.

I really hate Instagram by all my heart. It is the worst modern service with totally fucked API. It have bulk subscription but do not have bulk unsubscription.

I need to delete about  4500+ subscribers after my totally useless account had been stolen. It is the 5th attempt to do this simple (as I thought) action.
