### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by ALWIEZ** [ricardojoserf/instagram-followers-bot#7]
I think API of the Instagram has been changed.
All commands ;
`Login not successful
Traceback (most recent call last):
  File "main.py", line 157, in <module>
    main()
  File "main.py", line 113, in main
    for i in api.getTotalSelfFollowers():
  File "/home/alwiez/h/Social/instagram-followers-bot/LevPasha/InstagramAPI.py", line 162, in getTotalSelfFollowers
    return self.getTotalFollowers(self.username_id)
AttributeError: InstagramAPI instance has no attribute 'username_id'`

What should I do now?

**Comment by ALWIEZ** [comment]
My mistake sorry guys

**Comment by ricardojoserf** [comment]
No worries :)
